Header/footer/career details/company section/home page subnav
devcareer/team-heist pull request #15
Opened 2019-09-24 16:09 UTC by Techgurll

This is a compilation of all my part of the project. i.e Header,Footer,Company-A section,Career-details,Homepage sub navbar,Company subnavbar.

![Career details 1](https://user-images.githubusercontent.com/53382230/65529364-e8735a00-deed-11e9-9082-0b851a765393.png)
![career details 2](https://user-images.githubusercontent.com/53382230/65529367-e90bf080-deed-11e9-9510-ce40d104bffa.png)
![company section 2](https://user-images.githubusercontent.com/53382230/65529377-ea3d1d80-deed-11e9-985e-fa64329e1c6b.png)
![company video modal](https://user-images.githubusercontent.com/53382230/65529381-ec06e100-deed-11e9-8429-526bba65e735.png)
![company-section1](https://user-images.githubusercontent.com/53382230/65529389-edd0a480-deed-11e9-9dda-c030198f5b1c.png)
![company-subnavbar](https://user-images.githubusercontent.com/53382230/65529397-ee693b00-deed-11e9-9671-07de07ba0940.png)
![company-subnavbar2](https://user-images.githubusercontent.com/53382230/65529409-f1642b80-deed-11e9-963a-728d6427a723.png)
![cta-modal](https://user-images.githubusercontent.com/53382230/65529412-f2955880-deed-11e9-936c-47638b840bc7.png)
![cta-modal-sent](https://user-images.githubusercontent.com/53382230/65529413-f32def00-deed-11e9-94ec-e9c8b06e3163.png)
![Footer](https://user-images.githubusercontent.com/53382230/65529414-f3c68580-deed-11e9-9549-71390f82969a.png)
![Header](https://user-images.githubusercontent.com/53382230/65529415-f3c68580-deed-11e9-938a-20e37bf87da5.png)
![Homepage-subnavbar](https://user-images.githubusercontent.com/53382230/65529417-f45f1c00-deed-11e9-9137-37ea8bbe8ced.png)

2019-09-25 09:07 UTC, SEUNAGBEYE requested changes

2019-09-25 09:07 UTC, SEUNAGBEYE commented on scss/pages/_home.scss
> -.ctamodal{
Where did you move this deleted CSS to?

2019-09-25 09:07 UTC, SEUNAGBEYE commented on scss/pages/_about.scss
> -.companysection2{
Did you move this CSS somewhere?

2019-09-25 09:07 UTC, SEUNAGBEYE commented on scss/abstracts/mixins.scss
> -@mixin conTain {
Where did you move this to

2019-09-25 09:44 UTC, Techgurll commented on scss/pages/_home.scss
> -.ctamodal{
inside the homepage.scss

2019-09-25 09:44 UTC, Techgurll commented on scss/pages/_about.scss
> -.companysection2{
yes inside company.scss

2019-09-25 09:45 UTC, Techgurll commented on scss/abstracts/mixins.scss
> -@mixin conTain {
it is inside reset.scss as restriction

2019-09-26 20:11 UTC, SEUNAGBEYE approved these changes
LGTM

2019-09-26 20:20 UTC, SEUNAGBEYE commented
Raise a another PR for the fixes I mentioned on our call

2019-09-26 20:21 UTC, merged